library romanian;

Map<String, dynamic> values = {
  'universal': {
    'inapoi': 'Înapoi',
  },

  'adauga_metoda_plata': {
    'introduceti_datele_cardului': 'Introduceți datele cardului',
    'card_holder_title': 'CARDHOLDER',
    'valid_thru_title': 'VALID THRU',
    'expiry_date': '08/2028',
    'card_holder_hint': 'Card Holder',
    'card_number_text': 'XXXX XXXX XXXX XXXX',
    'adresa_web': 'https://www.paypal.com',
    'cvv': '322',
    'card_number_title': 'Card Number',
    'card_number_hint': '1453 2436 1198 4452',
    'necompletat': 'Necompletat',
    'incorect': 'Incorect',
    'nume': 'Nume',
    'card_holder_name_hint': 'Popescu',
    'cvv_title': 'CVV',
    'card_cvv': '● ● ●',
    'expired_date': 'Expired Date',
    'expiry_date_hint': '08/28',
    'necompletata': 'Necompletată',
    'incorecta': 'Incorectă',
    'plata_adauga': 'PLATĂ / ADAUGĂ',
  },

  'apel_video_pacient': {
    'va_rugam_asteptati': 'Vă rugăm așteptați după doctor să intre!',
  },

  'confirmare': {
    'confirmare_titlu': 'Confirmare',
    'master_card': 'Master Card',
    'card_number': '● ● ● ●  ● ● ● ●  ● ● ● ● 4455',
    'tip_plata': 'Paypal',
    'user': 'User',
    'banca': 'Bank',
    'stripe': 'Stripe',
    'adauga_metoda_de_plata': 'ADAUGĂ METODĂ DE PLATĂ',
  },

  'confirmare_servicii': {
    'confirma_plata': 'Confirmă plata',
    'servicii_pediatrie': 'Servicii Pediatrie',
    'primiti_recomandare_reteta': 'Primiți o recomandare și rețetă medicală',
    'ron': 'RON',
    'subtotal': 'Subtotal',
    'total': 'Total',
    'confirma_plata_buton': 'CONFIRMĂ PLATA',
  },

  'doctor_selection': {
    'search_hint': 'Medic primar pediatrie',
    'doctor_title': 'Dr. Daniela Pretoeasa',
    'doctor_spital': 'AIS Clinic & Hospital Bucharest',
    'doctor_specialitate_functie': 'Pediatrie, doctor primar',
    'doctor_localitate': 'București',
    'procent_useri_multumiti': '100%(254)',
    'perioada': '< 2 Ore',
  },

  'editare_cont': {
    'actualizare_finalizata_cu_succes':
        'Actualizare date finalizată cu succes!',
    'apel_invalid': 'Apel invalid!',
    'datele_nu_au_putut_fi_actualizate': 'Datele nu au putut fi actualizate!',
    'informatii_insuficiente': 'Informații insuficiente!',
    'eroare_la_executia_metodei': 'A apărut o eroare la execuția metodei!',
    'profilul_meu_titlu': 'Profilul meu',
    'email_hint': 'Email',
    'introduceti_email_valid': 'Introduceți un email valid!',
    'telefon_hint': 'Telefon',
    'introduceti_telefon_valid': 'Introduceți un număr de telefon valid!',
    'user_hint': 'User',
    'introduceti_utilizator': 'Introduceți un utilizator!',
    'numele_complet_hint': 'Numele complet',
    'introduceti_numele_complet': 'Introduceți numele complet!',
    'resetare_parola': 'Resetare parolă',
    'va_rugam_introduceti_parola': 'Vă rugăm introduceți o parolă!',
    'parola_trebuie_sa_contina':
        'Parola trebuie să aibă cel puțin 6 caractere!',
    'salvare_date': 'Salvare date',
  },

  'error_pacient': {
    'oops_text': 'Oops!',
    'detalii_text':
        'Procesul de schimbare parolă nu a reușit. Vă rugăm să reîncercați.',
    'resetare_parola': 'Resetare parolă',
  },

  'factura': {
    'date_format': 'MMM dd. yyyy',
    'limba': 'ro',
    'factura_titlu': 'Factură',
    'nume_factura': 'Plată - SOS Bebe',
    'email_emitent': 'Email :',
    'telefon_emitent': 'Telefon :',
    'titlu_pentru_beneficiar': 'Factură pentru:',
    'user_id': 'User Id:',
    'email_beneficiar': 'Email:',
    'telefon_beneficiar': 'Telefon:',
    'data_platii_titlu': 'Data plății',
    'data_platii_nume': 'Data plății',
    'procesata': 'Procesată',
    'detalii_factura': 'Detalii factură',
    'servicii': 'Servicii:',
    'numar': 'Număr:',
    'serie': 'Serie:',
    'valoare_cu_tva': 'Valoare cu TVA',
    'valoare_tva': 'Valoare TVA',
    'valoare_fara_tva': 'Valoare fără TVA',
    'buton_download_pdf': 'Download PDF',
    'trimite_testimonial': 'TRIMITE TESTIMONIAL',
  },

  'intro': {
    'gaseste_doctor_pediatru': 'Găsește cel mai bun Doctor Pediatru!',
    'gasiti_medici_specialisti':
        'Găsiți cei mai buni medici specialiști pentru copilul dvs.',
    'continua': 'CONTINUĂ',
  },

  'login': {
    'login_cu_succes': 'Login realizat cu succes!',
    'eroare_reintroduceti_user_parola':
        'Eroare! Reintroduceți user-ul și parola!',
    'telefon_email_utilizator_hint': 'Telefon, e-mail sau utilizator',
    'mesaj_introduceti_utilizator_email_telefon':
        'Introduceți un utilizator/email/numar de telefon valabil!',
    'parola': 'Parolă',
    'mesaj_introduceti_parola_noua': 'Vă rugăm introduceți o parolă nouă',
    'mesaj_introduceti_parola': "Vă rugăm introduceți parola",
    'mesaj_parola_cel_putin': 'Parola trebuie să aibă cel puțin 6 caractere',
    'ai_uitat_parola': 'Ai uitat parola?',
    'conectare': 'CONECTARE',
    'or': 'OR',
    'conectare_cu_facebook': 'CONECTARE CU FACEBOOK',
    'conectare_cu_google': 'CONECTARE CU GOOGLE',
    'nu_ai_cont': 'NU AI CONT?',
    'inscrie_te': ' ÎNSCRIE-TE!',
  },

  'main': {
    'titlu': 'SOS Bebe',
  },

  'parola_noua_pacient': {
    'mesaj_parola_resetata_cu_succes': 'Parolă resetată cu succes!',
    'apel_invalid': 'Apel invalid!',
    'eroare_resetare_parola': 'Eroare la resetare parolă!',
    'informatii_insuficiente': 'Informații insuficiente!',
    'a_aparut_o_eroare': 'A apărut o eroare la execuția metodei!',
    'parola_noua': 'Parola nouă',
    'reseteaza_parola_text': 'Introduceți o nouă parolă',
    'parola_hint': 'Parolă',
    'introduceti_parola_noua': 'Vă rugăm introduceți o parolă nouă',
    'parola_cel_putin': 'Parola trebuie să aibă cel puțin 6 caractere',
    'parola_aceeasi': 'Parola trebuie să fie aceeași în ambele câmpuri',
    'repeta_noua_parola': 'Repetă noua parolă',
    'se_incearca_resetarea_parolei': 'Se încearcă resetarea parolei',
    'confirma': 'Confirmă',
  },

  'plata_esuata': {
    'plata_esuata_titlu': 'Plată eșuată',
    'fonduri_insuficiente':
        'S-ar putea să nu aveți suficiente fonduri în cont pentru a plăti. Verificați soldul contului sau contactați-vă banca. Card de credit sau de debit neeligibil.',
    'continua': 'CONTINUĂ',
  },

  'plata_succes': {
    'plata_succes_titlu': 'Plată realizată cu succes',
    'va_multumim_detalii':
        'Vă mulțumim! Detaliile dvs. de plată vor fi trimise la adresa dvs. de e-mail.',
    'va_multumim_simplu': 'Vă mulțumim! ',
    'vei_fi_redirectionat': 'Vei fi redirectionat ...',
  },

  'plati': {
    'date_format': 'dd MMMM yyyy',
    'limba': 'ro',
    'titlu': 'Plăți',
    'data_platii_titlu': 'Data plății',
    'suma_platii_titlu': 'Suma plății',
  },

  'profil_doctor_disponibilitate_servicii': {
    'date_format': 'dd MMMM yyyy',
    'limba': 'ro',
    'moneda_ron': 'RON',
    'moneda_euro': 'EURO',
    'scrie_intrebare': 'Scrie o întrebare',
    'suna_acum': 'Sună acum',
    'primiti_recomandare': 'Primiți o recomandare și rețetă medicală',
    'sumar_titlu': 'Sumar',
    'titlu_profestional': 'Titlu profesional',
    'specializare': 'Specializare',
    'experienta': 'Experiență',
    'loc_de_munca': 'Loc de muncă',
    'activitate': 'Activitate',
    'utilizatori_multumiti': 'Utilizatori mulțumiți: ',
    'am_ajutat': 'Am ajutat',
    'pacienti': 'pacienți',
    'ai_aplicatiei': ' ai aplicației',
    'testimoniale': 'Testimoniale',
    'recenzii': 'Recenzii',
    'in_consultatie': ' în consultație',
    'rating': 'Rating',
    'medic_adaugat_cu_succes': 'Medic adăugat cu succes!',
    'medic_adaugat_apel_invalid': 'Apel invalid!',
    'medic_neadaugat': 'Medicul nu a fost adăugat la favorite!',
    'medic_adaugat_informatii_insuficiente': 'Informații insuficiente!',
    'medic_adaugat_a_aparut_o_eroare': 'A apărut o eroare la execuția metodei!',
    'medic_scos_cu_succes': 'Medic scos cu succes!',
    'medic_scos_apel_invalid': 'Apel invalid!',
    'medic_nescos': 'Medicul nu a fost scos de la favorite!',
    'medic_scos_informatii_insuficiente': 'Informații insuficiente!',
    'medic_scos_a_aparut_o_eroare': 'A apărut o eroare la execuția metodei!',
  },

  'profil_pacient': {
    'cod_trimis_cu_succes': 'Cod trimis cu succes!',
    'apel_invalid': 'Apel invalid!',
    'cont_inexistent': 'Cont inexistent!',
    'cont_existent_fara_date_contact':
        'Cont existent dar clientul nu are date de contact!',
    'a_aparut_o_eroare': 'A apărut o eroare la execuția metodei!',
    'profilul_meu_titlu': 'Profilul meu',
    'editare_cont': 'Editare cont',
    'doctori_salvati': 'Doctori Salvati',
    'nu_exista_facturi_de_afisat': 'Nu există facturi de afișat!',
    'vezi_plati': 'Vezi Plăti',
    'GDPR': 'GDPR',
    'dezactivare_cont': 'Dezactivare cont',
    'deconectare': 'Deconectare',
    'termeni_si_conditii': 'Termeni și Condiții',
    'informatii_insuficiente': 'Informații insuficiente!',
  },

  'questionare': {
    'date_chestionar_trimise_cu_succes': 'Date chestionar trimise cu succes!',
    'apel_invalid': 'Apel invalid!',
    'datele_nu_au_putut_fi_trimise': 'Datele nu au putut fi trimise!',
    'a_aparut_o_eroare': 'A apărut o eroare la execuția metodei!',
    'chestionar': 'Chestionar',
    'nume_prenume_pacient': 'Nume și prenume pacient',
    'nume_copil_hint': 'Nume copil',
    'introduceti_nume_prenume_pacient':
        'Introduceti numele și prenumele pacientului!',
    'data_nastere': 'Data naștere',
    'date_format': 'dd.MM.yyyy',
    'data_nastere_hint': 'Data naștere',
    'introduceti_data_nastere': 'Introduceți o dată de naștere!',
    'greutate': 'Greutate',
    'numar_kilograme': 'Număr kilograme',
    'introduceti_numar_kilograme': 'Introduceti numărul de kilograme',
    'alergic_la_medicament': 'Alergic la vreun medicament?',
    'la_ce_medicament_este_alergic': 'La ce medicament este alergic?',
    'alergic_la_paracetamol': 'Alergic la paracetamol...',
    'simptome_pacient': 'Simptome pacient',
    'febra': 'Febră',
    'tuse': 'Tuse',
    'dificultati_respiratorii': 'Dificultăți respiratorii',
    'astenie': 'Astenie',
    'cefalee': 'Cefalee',
    'dureri_in_gat': 'Dureri în gât',
    'greturi_varsaturi': 'Grețuri/Vărsături',
    'diaree_constipatie': 'Diaree/Constipație',
    'refuzul_alimentatie': 'Refuzul alimentație',
    'iritatii_piele': 'Iritații piele',
    'nas_infundat': 'Nas înfundat',
    'rinoree': 'Rinoree',
    'trimite_chestionarul': 'TRIMITE CHESTIONARUL',
  },

  'raspunde_intrebare_doar_chat': {
    'apel_mesaje': 'Apel mesaje',
    'nume_pacient': 'Nume pacient',
    'trimite_media': 'Trimite media',
    'nu_aveti_nici_un_mesaj': 'Nu aveți nici un mesaj încă',
    'fisier_mesaj_chat': 'Fișier',
    'scrie_mesaj': 'Scrie un mesaj...',
    'trimite': 'Trimite',
    'mesaje_necitite': 'Mesaje necitite',
  },

  'raspunde_intrebare_medic': {
    'imagine': 'Imagine',
    'fisier': 'Fișier',
    'anuleaza': 'Anulează',
    'nume_pacient': 'Nume pacient',
    'trimite_media': 'Trimite media',
    'nu_aveti_nici_un_mesaj': 'Nu aveți nici un mesaj încă',
    'fisier_mesaj_chat': 'Fișier',
    'scrie_mesaj': 'Scrie un mesaj...',
    'trimite': 'Trimite',
    'marcheaza_mesajul_ca_necitit': 'Marchează mesajul ca necitit',
  },

  'register': {
    'inregistrare_cu_succes': 'Înregistrare finalizată cu succes!',
    'apel_invalid': 'Apel invalid!',
    'cont_deja_existent': 'Cont deja existent!',
    'informatii_insuficiente': 'Informații insuficiente!',
    'a_aparut_eroare': 'A apărut o eroare la execuția metodei!',
    'telefon_email_utilizator_hint': 'Telefon, e-mail sau utilizator',
    'introduceti_utilizator_email_telefon_valid':
        'Introduceți un utilizator/email/numar de telefon valid!',
    'nume_complet_hint': 'Nume Complet',
    'introduceti_numele_complet': 'Vă rugăm introduceți numele complet!',
    'parola': 'Parolă',
    'introduceti_parola': 'Vă rugăm introduceți o parolă!',
    'parola_cel_putin': 'Parola trebuie să aibă cel puțin 6 caractere!',
    'se_incearca_inregistrarea': 'Se încearcă înregistrarea',
    'inainte': 'ÎNAINTE',
    'daca_te_inscrii': 'Dacă te înscrii, îți exprimi acordul cu ',
    'conditii_utilizare': 'Condițiile de utilizare.',
    'din': 'Din ',
    'politica_de_confidentialitate': 'Politica de confidențialitate',
    'poti_afla_cum_colectam':
        ' poți afla cum colectăm, folosim și distribuim datele tale, iar din ',
    'politica_de_utilizare': 'Politica de utilizare a modulelor cookie',
    'poti_afla_cum_utilizam':
        ' poți afla cum utilizăm modulele cookie și tehnologii similare. ',
    'ai_un_cont': 'Ai un cont? ',
    'conecteaza_te': 'Conectează-te',
  },

  'reset_password_pacient': {
    'reseteaza_parola_titlu': 'Resetează parola',
    'reseteaza_parola_text_mijloc':
        'Introdu numărul de telefon pentru a-ți schimba parola contului',
    //'telefon_email_utilizator_hint': 'Telefon, e-mail sau utilizator',
    'telefon_email_utilizator_hint': 'Telefon',
    'introduceti_utilizator_email_telefon':
        'Introduceți un utilizator/email/numar de telefon valid!',
    'contul_dumneavoastra':
        'Contul dumneavoastră nu conține informațiile de contact pentru a reseta parola, vă rugăm să contactați un reprezentant SOS Bebe',
    'send_code': 'Trimite cod',
    'cod_trimis_cu_succes': 'Cod trimis cu succes!',
    'apel_invalid': 'Apel invalid!',
    'cont_inexistent': 'Cont inexistent!',
    'cont_existent_fara_date':
        'Cont existent dar clientul nu are date de contact!',
    'a_aparut_o_eroare': 'A apărut o eroare la execuția metodei!',
  },

  'succes_pacient': {
    'felicitari': 'Felicitări!',
    'text_mijloc': 'Ați modificat parola cu succes!',
    'log_in': 'Log in',
  },

  'termeni_si_conditii': {
    'termeni_si_conditii_titlu': 'Termeni și condiții',
    'termeni_si_conditii_text': 'Termeni și condiții text',
    'go_home': 'Go home',
  },

  'testimonial': {
    'feedback_trimis_cu_succes': 'Feedback trimis cu succes!',
    'apel_invalid': 'Apel invalid!',
    'feedback_netrimis': 'Feedback-ul nu a fost trimis!',
    'informatii_insuficiente': 'Informații insuficiente!',
    'a_aparut_o_eroare': 'A apărut o eroare la execuția metodei!',
    'va_multumim': 'Vă mulțumim!',
    'rating': 'Rating',
    'te_rugam_sa_lasi_un_testimonial': 'Te rugăm să ne lași si un testimonial!',
    'doctorul_a_raspuns_hint': 'Doctorul a raspuns rapid...',
    'se_incearca_trimiterea': 'Se încearcă trimiterea feedback-ului!',
    'trimite_testimonialul': 'TRIMITE TESTIMONIALUL',
  },

  'verifica_codul_pacient': {
    'verifica_codul': 'Verifică codul',
    'text_mijloc': 'Introdu codul primit prin SMS',
    'trimite_din_nou_codul': 'Timite din nou codul',
    'verifica': 'Verifică',
    'cod_verificat_cu_succes': 'Cod verificat cu succes!',
    'apel_invalid': 'Apel invalid!',
    'eroare_cod_neverificat': 'Eroare! Codul nu a putut fi verificat!',
    'informatii_insuficiente': 'Informații insuficiente!',
    'a_aparut_o_eroare': 'A apărut o eroare la execuția metodei!',
  },

  'verifica_pin_sterge_cont': {
    'verifica_codul_sterge_cont_titlu': 'Verifică codul și șterge contul',
    'text_mijloc': 'Introdu codul primit prin SMS',
    'trimite_din_nou_codul': 'Timite din nou codul',
    'se_verifica_codul_trimis': 'Se verifică codul trimis',
    'se_sterge_contul': 'Se sterge contul',
    'verifica_pin_sterge_cont_buton': 'Verifică pin și șterge cont',
    'cod_verificat_cu_succes': 'Cod verificat cu succes!',
    'apel_invalid': 'Apel invalid!',
    'eroare_cod_neverificat': 'Eroare! Codul nu a putut fi verificat!',
    'informatii_insuficiente': 'Informații insuficiente!',
    'a_aparut_o_eroare': 'A apărut o eroare la execuția metodei!',
    'cont_sters_cu_succes': 'Cont șters cu succes!',
    'apel_invalid_sterge_cont': 'Apel invalid!',
    'eroare_cont_nesters': 'Eroare! Contul nu a putut fi șters!',
    'informatii_insuficiente_sterge_cont': 'Informații insuficiente!',
    'a_aparut_o_eroare_sterge_cont': 'A apărut o eroare la execuția metodei!',
  },

  'vezi_medici_disponibili_intro': {
    'vezi_medici_disponibili_titlu': 'Vezi medici disponibili',
    'aceasta_aplicatie_text':
        'Acestă aplicație dorește să vină în sprijinul părinților oferind sfaturi medicale profesioniste, la orice oră din zi sau din noapte.',
    'medicii_nostri_text':
        'Medicii noștri acordă asistență pediatrică de prima intervenție cu scopul de a liniști temerile părinților și a ameliora simptome copiilor până la un consult în persoană cu medicul pediatru sau de familie.',
    'atentie_text':
        'Atenție! În cazul în care viața copilului este în pericol, vă rugăm să apelați numărul unic de urgențe 112 sau să vă adresați Unităților de Primire Urgențe.',
  },

  'vezi_medici_salvati': {
    'profilul_meu': 'Profilul meu',
    'medici_online': 'Medici online',
    'toti_medicii': 'Toți medicii',
    'scrie_o_intrebare': 'Scrie o întrebare',
    'consultatie_video': 'Consultație video',
    'interpretare_analize': 'Interpretare analize',
    'in_consultatie': ' în consultație',
  },

  'vezi_toti_medicii': {
    'profilul_meu': 'Profilul meu',
    'medici_online': 'Medici online',
    'toti_medicii': 'Toți medicii',
    'scrie_o_intrebare': 'Scrie o întrebare',
    'consultatie_video': 'Consultație video',
    'interpretare_analize': 'Interpretare analize',
    'in_consultatie': ' în consultație',
  },

/////////////////////////////////////////////////////////////////////////////////

  // old Adrian Murgu
  'overrides': {
    'searchTextFieldPlaceholderLabel': 'Căutați',
    'timerPickerHourLabels': {'ora': 'Ora', 'ore': 'ore'},
    'timerPickerMinuteLabels': 'Min',
    'timerPickerSecondLabels': 'Sec',
    'alertDialogLabel': 'Info',
    'datePickerHourSemanticsLabel': 'Ora',
    'datePickerMinuteSemanticsLabel': {'minut': '1 Minut', 'minute': 'Minute'},
    'timerPickerHourLabel': {'ora': 'Ora', 'ore': 'ore'},
    'timerPickerMinuteLabel': 'Min',
    'timerPickerSecondLabel': 'Sec',
    'cutButtonLabel': 'decupare',
    'copyButtonLabel': 'copiere',
    'pasteButtonLabel': 'lipire',
    'selectAllButtonLabel': 'Selectați tot',
    'todayLabel': 'Azi',
    'datePickerMediumDate': {
      'shortWeekdays': [
        'Lun',
        'Mart',
        'Mie',
        'Joi',
        'Vin',
        'Sâm',
        'Dum',
      ],
      'shortMonths': [
        'Ian',
        'Feb',
        'Mar',
        'Apr',
        'Mai',
        'Iun',
        'Iul',
        'Aug',
        'Sep',
        'Oct',
        'Noi',
        'Dec',
      ],
      'months': [
        'Ianuarie',
        'Februarie',
        'Martie',
        'Aprilie',
        'Mai',
        'Iunie',
        'Iulie',
        'August',
        'Septembrie',
        'Octombrie',
        'Noiembrie',
        'Decembrie',
      ]
    }
  },
  /*
  'universal': {
    'lss':'Listă servicii:',
    'v':'Valoare:',
    'p':'Plătit:',

    'cpi':'Copiii dumneavostră (numele complet), separați prin virgulă',
    'cc':' Cont nou',
    'tff':'Modificați Numărul de Telefon',
    'malll':'Modificați mail-ul',
    'ds':'Descriere',
    'ai':'Arii de interes',
    'dmd':'Detalii medic',
    'textCont':'Vă rugăm să completați toate câmpurile de\n mai jos, pentru a vă putea crea un cont.',
    'textlogare':'Pentru logare, vă rugăm să introduceți \nadresa de email și parola.',
    'languageTitle': 'Selectați limba',
    'eroareServer': 'Am întâmpinat o problemă. Vă rugăm încercați mai târziu.',
    'campInvalid': 'Câmp invalid',
    'mandatoryField': 'Câmp obligatoriu',
    'telefonInvalid': 'Telefonul nu este valid',
    'emailInvalid': 'Adresa de email nu este validă',
    'telefon': 'Telefon ',
    '1':'Scrisoare medicală',
    '2':'Rețetă medicală',
    '3':'Adeverintă medicală',
    'judet' : 'Județ',
    'stergecont' : 'Șterge contul',
    'cons':'Consultații',
    'mc':'Modificați parola ',
    'nmx' : 'Modificați numele',
    'localitate':'Localitate',
    'ml' : 'Modificați localitatea',
    'jd' : 'Modificați județul',
    'pn' : 'Modificați prenumele',
    'sal' : 'Salvează',
    'email': 'Email',
    'back': 'Înapoi',
    'continue': 'Continuă',
    'yes': 'Da',
    'no': 'Nu',

    'nume': 'Nume',
    'prenume': 'Prenume',
    'ddn': 'Data de naștere',
    'password': 'Parola',
    'passwordConfirm': 'Confirmați parola',
    'register': 'Nu ai cont? ',
    'login': 'Intră în cont',
    'send': 'Creare cont',
    'ok': 'Ok',
    'anulare': 'Anulare',
    'deschide_setari': 'Deschide setări',
    'passMismatch': 'Parolele nu se potrivesc',
    'invalidCredentials': 'Datele introduse nu sunt valide. Introduceți datele de conectare și reîncercați.',
    'forgotPass': 'Resetează parola',
    'changePass': 'Resetează parola',
    'newPassword': 'Noua parolă',
    'pinEmailAlert': 'Pe adresa de email menționată a fost trimis un cod de verificare, vă rugăm introduceți codul:',
    'validationCode': 'Cod validare',
    'validationCodeError': 'Codul introdus nu este valid',
    'errorRegister132': 'Există deja un cont cu acest email!',
    'ddn_peste_18ani': 'Trebuie să aveți cel puțin 18 ani împliniți',
    'minim_caractere': 'Parola trebuie să aibă minim 6 caractere',
    'loginDateGresite': 'Date de autentificare greșite',
    'reseteazaParolaDateGresite': 'Acest email nu există în baza de date',
    'reseteazaParolaValideazaPin': 'Validează',
    'pinInvalid': 'Codul introdus nu este valid',
    'mesajUserNeasociat':
        'Momentan nu sunteți asociat unui dosar de pacient al clinicii noastre. Pentru mai multe detalii vă rugăm să contactați recepția clinicii.',
    'appUnavailable': 'Aplicație indisponibilă',
    'inchide': 'Închide',
    'selectati_sediul': 'Selectați sediul',
    'toate_sediile': 'Toate',
    'pinVal':'Validare PIN',

  },
  */

  'noInternet': {
    'noInternet': 'Vă rugăm să verificați conexiunea la internet',
    'refresh': 'Încercați din nou'
  },
  'askPhoneEmail': {
    'tel': 'Introduceți numărul de telefon:',
    'email': 'Introduceți adresa de email:',
    'cancel': 'Anulare'
  },
  'accepta_termenii': {
    'text1':
        'Apăsați "Acceptă & Continuă" pentru a vă da acordul în privința termenilor și condițiilor de confidențialitate.',
    'termeni': 'Termeni si Conditii',
    'welcome': 'Bine ați venit!',
    'patient': 'PATIENT',
    'healthcare': 'HEALTHCARE',
    'msg': 'Apăsați "Acceptă & Continuă" pentru a vă da acordul în privința',
    'msg_terms': 'termenilor',
    'msg_and': 'și',
    'msg_conditions': 'condițiilor de confidențialitate',
    'accepta_termenii': 'Acceptă & Continuă'
  },
  'termeni_conditii': {'title': 'Termeni și condiții'},
  'politica_conf': {'title': 'Politica de Confidențialitate'},

  'home': {
    'hp': 'Plăți',
    'h11':
        'Momentan nu au fost gasite plati neefectuate în dosarul dumneavoastra electronic',
    'h22':
        'Momentan nu au fost gasite plati în dosarul dumneavoastra electronic',
    'alc': 'Alegeți pacientul',
    'ds': 'Detalii consultație',
    'rpg': 'Reprogramare',
    'irt': 'Intră in consultație',
    'vd': 'Vezi detalii',
    'pg': 'Pediatrie generală',
    'mkc': 'Modificare cont',
    'modS': 'Modificări Salvate',
    'confident':
        'iStoma este un soft de gestiune a clinicilor si cabinetelor stomatologice dezvoltat, intretinut si comercializat de IDAVA SOLUTIONS SRL, cu sediul în ELECTROMAGNETICA BUSINESS PARK, Sector 5, București, înmatriculată la Registrul Comerțului sub numărul J40/20674/17.10.2022, având CUI RO30410797.\nCE INFORMAȚII COLECTĂM?\nINFORMAȚIILE OFERITE VOLUNTAR ȘI CONȘTIENT\nîn momentul în care completați un formular de contact. Prelucrăm datele dumneavoastră cu caracter personal pentru a vă putea răspunde la întrebări sau pentru a putea presta serviciile pe care le solicitați sau comandați. Date personale înseamnă orice informație care poate fi legată de o persoană fizică identificată sau identificabilă. Datele personale includ toate tipurile de informații directe sau indirecte, cum ar fi numele complet, adresa de email sau numărul de telefon.\nÎn cazul în care comandați produse de la noi, avem nevoie de aceste informații să vă putem livra produsele comandate.\nAceste informații vor fi stocate în perioada garanției serviciilor sau ale produselor pentru a vă putea contacta în cazul în care este necesar, dar strict legat de produsele și serviciile comandate.\n\n În cazul serviciilor care se reînnoiesc automat, avem nevoie de datele dvs. pentru a emite facturile viitoare și a le trimite pe adresa dvs. în formă electronică sau fizică.\nÎn cazul în care solicitați mai multe informații despre noi printr-un formular sau telefonic, vom utiliza adresa dvs. de email pentru a vă trimite unul sau mai multe mail-uri prin care vă prezentăm serviciile noastre, dar numai în urma unei solicitări concrete și exprese. Adițional dacă specificați numărul de telefon, este posibil să vă sunăm pentru a solicita mai multe informații sau pentru a răspunde la întrebările trimise.\nINFORMAȚII COLECTATE ÎN MOD AUTOMAT\nAdițional site-ul nostru colectează informații despre paginile vizitate și interacțiunea cu conținutul site-ului. Aceste activități vor fi salvate în istoric și vor fi utilizate pentru a analiza erorile apărute și pentru a îmbunătăți site-ul. Aceste log-uri vor conține și adresa dvs. de IP, informații despre browser-ul utilizat cât și despre dispozitivul hardware utilizat (modelul, sistemul de operare, identificator unic al dispozitivului, informații despre rețeaua de pe care vă conectați). Site-ul va plasa și un cookie pe dispozitivul de pe care îl accesați, urmând să fie utilizat pentru identificarea indirectă. Aceste informații nu vor fi utilizate decât pentru operarea site-ului, măsurarea performanței site-ului, traficului și rezultatele campaniilor de marketing. Nu vom vinde sau transfera aceste informații terților, indiferent de raporturile în care suntem cu aceștia, și vom păstra o strictă confidențialitate a lor. Aceste informații nu vor fi utilizate pentru a vă contacta (email, sms sau telefonic), ci pentru a îmbunătăți site-ul nostru, pentru a vă oferi informații relevante, pentru a studia exact ce căutați și a răspunde la întrebări.\nSite-ul nostru utilizează următoarele servicii externe pentru a colecta informațiile:\nGoogle Analitics\nGoogle Adwords și tracking\nFacebook și Facebook pixel\nYoutube\nCum păstrăm datele dvs. cu caracter personal?\nTrebuie să știți că datele personale pe care le-am colectat de la dvs. pot fi accesate doar de echipa noastră și în cazuri excepționale, doar în urma unui demers legal, de instituțiile publice din România care aplică legea.\n\nPrelucrăm datele cu caracter personal aplicând măsurile tehnice și organizatorice adecvate pentru a le proteja împotriva oricărei prelucrări ilegale, distrugerii sau pierderii accidentale sau intenționate, a alterării, divulgării, transmiterii neautorizate sau accesului neautorizat, inclusiv când respectivele date pot fi transmise prin rețea.\nVă rugăm să ne contactați pe adresa de email contact@istoma.ro pentru:\norice neregulă în funcționarea site-ului\norice suspiciune privind insecuritatea aplicației\norice solicitare în legatură cu exercitarea oricărui drept ce vă revine în temeiul legii',
    'sd': 'Caută medic sau specialitate',
    'welcome': 'Bine ați venit pe',
    'tap_to_pay': 'Tap to pay',
    'sus': 'Bine ați venit ',
    'contul_meu': 'Contul meu',
    'interventii': 'Istoric consultații',
    'programari': 'Programări',
    'contact': 'Contact',
    'programarileMele': 'Programări',
    'card': 'Plăți',
    'programariFamilie': 'Programări familie',
    'programareNoua': 'Programare nouă',
    'listaPreturi': 'Lista de prețuri',
    'echipaDoctori': 'Echipă medicală',
    'tratamenteleMele': 'Tratamente',
    'radiografii': 'Arhivă medicală',
    'prescriptiileMele': 'Prescripții',
    'sold': 'Sold curent',
    'logout': 'Log out',
    'schimbaLimba': 'Schimbă limba',
    'feedback': 'Feedback',
    'sedii': 'Sedii',
    'programari_viitoare': 'Programări viitoare',
    'programari_trecute': 'Programări trecute',
    'urmatoarea_programare':
        'Următoarea programare este pe _DATA_, la Medicul _MEDIC_.',
    'confirma': 'Intră în consultație',
    'anuleaza': 'Reprogramează',
    'de_facut': 'De făcut',
    'realizate': 'Realizate',
    'h1': 'Nu ai nici o programare',
    'h2': 'Nu uita: "Mai bine să previi decât să tratezi!"',
    'nicio_programare':
        'Nu aveți nicio o consultație anterioară;\n \nNu uitați: "Mai bine să previi decât să tratezi"',
    'nicio_consultatie': 'Nu aveți nici o consultație anterioară',
    'nicio_interventie':
        'Nu aveți prevăzute tratamente;\nNu uitați "Mai bine să previi decât să tratezi!"',
    'anuleaza_programarea': 'Anulați programarea?',
    'confirma_programarea': 'Confirmați programarea?',
    'yes': 'Da',
    'no': 'Nu',
    'solicitaProgramare': 'Solicită programare',
    'veziIstoric': 'Vezi istoric',
    'istoricProgramari': 'Istoric programări',
    'oProgramare1': 'Următoarea dumneavoastră programare este pe ',
    'oProgramare2': 'de la',
    'oProgramare3': 'la ',
    'maiMulteProgramari': 'Aveți următoarele programări:',
    'maiMulteProgramariLa': 'la ',
    'areProgramare': 'are programare'
  },
  'chooseUser': {'pentru': 'pentru', 'mine': 'mine'},
  'contul_meu': {
    'titlu': 'Contul meu',
    'va_putem_contacta': 'Vă putem contacta la:',
    'ne_permiteti': 'Ne permiteți să trimitem:',
    'sms_reamintire': 'SMS de reamintire a programării',
    'sms_recall': 'SMS de recall/profilactic',
    'sms_aniversare': 'SMS de aniversare',
    'newsletter_sms': 'Newsletter SMS',
    'newsletter_email': 'Newsletter Email',
    'modificati': 'Modificați',
    'Nume Personal': 'Nume Personal',
    'Prenume Personal': 'Prenume ',
    'lipsa_telefon':
        'Fără telefonul dumneavoastră, în situația excepțională în care medicul dumneavoastră întâmpina o problema și nu poate onora programarea, noi nu vă vom mai putea anunța cu privire la situația intervenită.',
    'lipsa_email':
        'Fără adresa dumneavoastră de email puteți rata ofertele noastre periodice.',
    'sigur_doriti': 'Sigur doriți acest lucru?',
    'da': 'Da',
    'nu': 'Nu',
    'lipsa_sms_reamintire':
        'În situația excepțională în care medicul dumneavoastră întâmpină o problema și nu poate onora programarea, noi nu vă vom mai putea anunța cu privire la situația intervenită.',
    'lipsa_sms_recall':
        'Vă trimitem SMS de recall atunci când starea dumneavoastră medicală sau păstrarea acesteia fac necesar acest lucru. Prin bifarea căsuței NU, noi nu vă vom mai putea contacta în acest scop.',
    'preferinte': 'Preferințe comunicare',
    'date_contact': 'Date contact',
    'save': 'Salvați',
    'cancel': 'Anulează',
    'schimba_limba': 'Schimbă limba',
    'schimba_parola': 'Schimbă parola',
    'email_deja_folosit': 'Acest email este deja folosit',
    'cod_de_bare': 'Cod de bare',
    'alege': 'Alege',
    'pacient': 'Pacient',
    'msgSigurDoritiStergerea': 'Sigur doriți ștergerea contului?',
  },
  'schimba_parola': {
    'current_pass': 'Parola actuală',
    'incorect_pass': 'Parolă incorectă',
  },
  'poza_profil': {
    'titlu': 'Poză de profil',
    'schimba_poza': 'Schimbă poza',
    'camera': 'Cameră',
    'galerie': 'Galerie',
    'always_finish_activities_msg':
        'Aplicația nu poate face poze dacă aveți setarea "Nu păstrați activitățile" activată. Puteți dezactiva această opțiune din meniul "Opțiuni dezvoltator"',
    'cere_permisiune_camera':
        'Aplicația are nevoie de permisiunea dumneavoastră pentru a putea face poze.',
    'cere_permisiune_galerie':
        'Aplicația are nevoie de permisiunea dumneavoastră pentru a putea accesa pozele.'
  },
  'programareNoua': {
    'aleDat': 'Selectează dată',
    'pentruMine': 'Pentru mine',
    'alegetiData': 'Vă rugăm să alegeți o dată',
    'alegetiAltaData':
        'Nu sunt intervale libere în data selectată. Vă rugăm să alegeți o alta dată.',
    'completatiObservatii': 'Vă rugăm să completați câmpul Observații',
    'progAdaugata': 'Solicitarea a fost trimisă',
    'progAdaugataReala': 'Programarea a fost adaugată',
    'categorie': 'Specialitate medicală',
    'medic': 'Medic',
    'data': 'Dată',
    'observatii': 'Observații',
    'scrn': 'Scrie-ne mai multe',
    'alegeti': 'Alegeți',
    'alegetiCategoria': 'Alege specialitatea medicală',
    'alegetiServiciul': 'Alege serviciul',
    'alegeListaDeServicii': 'Alege lista de servicii',
    'alegeServiciul': 'Alege serviciul :',
    'alegetiMotiv': 'Vă rugăm să alegeți unul dintre motive',
    'alegetiMedicul': 'Alege medic',
    'alegetiOra': 'Vă rugăm să alegeți o oră',
    'faraIntervaleLibere': 'Nu sunt intervale libere',
    'faraIntervaleLibereLaMedic':
        'Nu sunt intervale libere la medicul selectat',
    'urmatorulInterval':
        'Primul interval disponibil este pe DATA incepand cu ora INTERVAL.',
    'intervaleDisponibile': 'Intervale disponibile',
    'ok': 'Ok',
    'trimite': 'Solicita Programare',
    'urmatorulpas': 'Următorul pas',
    'nuSuntServiciiAlocateSpecializarii':
        'Nu exista servicii alocate specializarii',
    'eroare': 'Eroare',
    'selectatiUnServiciu': 'Selectați un serviciu pentru a continua',
    'nuAtiSelectatUnMedic': 'Nu ați selectat un medic.',
    'nuAtiSelectatOCategorie': 'Nu ați selectat o categorie!',
    'alegetiListaServicii': 'Alegeti o lista de servicii!',
    'alegetiOData': 'Alegeți o dată',
    'selectatiIntervalMedic':
        'Vă rugăm să selectați un interval orar si un medic înainte de a continua.',
    'rezumatProgramare': 'Rezumat programare',
    'rezumatProgramareMedic': 'Medic:',
    'rezumatProgramareCategorie': 'Categorie:',
    'rezumatProgramareServiciuSelectat': 'Serviciul Selectat:',
    'rezumatProgramareData': 'Programare pe data de:',
    'rezumatProgramareOra': 'la ora:',
    'rezumatProgramarePretul': 'Prețul:',
  },
  'programarileLui': {
    'viitoare': 'Viitoare',
    'trecute': 'Complete',
    'nicioProgViitoare': 'Nicio programare viitoare',
    'nicioProg': 'Nicio programare',
    'nicioSolicitare': 'Nicio solicitare',
    'anulata': 'Anulată',
    'solicitari': 'Solicitări',
    'nuSuntDocumente': 'Nu există documente',
  },
  'tratamenteleLui': {
    'realizate': 'Realizate',
    'deFacut': 'De făcut',
    'niciunTratamentDeFacut': 'Niciun tratament de făcut',
    'niciunTratamentRealizat': 'Niciun tratament realizat'
  },
  'prescriptii': {
    'iv': 'Investigații și prețuri',
    'prs': 'Prescripţii medicale',
    'niciuna': 'Nici o prescripție',
    'descarca': 'Descarcă',
    'momentanNuAuFostGasitePrescriptii':
        'Momentan nu au fost găsite prescripții în dosarul dumneavoastră electronic',
  },
  'prices': {
    'appBarTitle': 'Lista de prețuri',
    'search': 'Căutați...',
    'cancel': 'Anulați',
    'category': 'Specializare',
    'code': 'Cod',
    'name': 'Denumire',
    'price': 'Preț',
    'all': 'Toate specializarile',
    'RON': 'Preț (lei)',
  },
  'sold': {
    'sold': 'Soldul dumneavoastră la acest moment este:',
    'iban': 'IBAN-ul la care puteți plăti este:',
    'soldCopied': 'Soldul a fost copiat în clipboard',
    'ibanCopied': 'IBAN-ul a fost copiat în clipboard',
    'detailsCopied': 'Detaliile au fost copiate în clipboard',
    'infoDetalii': 'Vă rugăm ca la detaliile plății să treceți:',
    'plataProforma': 'Plată proformă',
    'plataFactura': 'Plată factură',
    'plata': 'Plată',
    'veziDetalii': 'Vezi detalii',
  },
  'soldDetalii': {
    'title': 'Detalii sold',
    'data': 'Data',
    'doctor': 'Medic',
    'interventie': 'Intervenție',
    'pret': 'Preț',
    'achitat': 'Achitat',
    'deAchitat': 'De achitat',
    'dinti': 'Dinți',
    'total': 'Rest de plată',
    'subtotal': 'Subtotal',
  },
  'feedback': {
    'intrebare': 'Cum evaluați ultima vizită la noi?',
    'observatii': 'Observații',
    'buton': 'Trimite',
    'completatiObs': 'Vă rugăm să completați câmpul observații',
    'acordaRating': 'Vă rugăm să acordați un rating'
  },
  'sedii': {
    'as': 'Alege Sediul',
    'harta': 'Harta',
    'hint': 'Lăsați-ne un mesaj',
    'btn': 'Trimite',
    'trimite_empty': 'Vă rugăm să completați câmpul.',
    'trimite_success': 'Mesajul dumneavoastră a fost transmis.',
  },
  'radiografii': {
    'c1': 'Clinică pediatrică',
    '1.1': '1. Aspecte Generale',
    '1.2':
        'Prezentele Termeni și Condiții („Termeni și Condiții”) guvernează raporturile dintre IDAVA SOLUTIONS S.R.L., societatea care dezvoltă și întreține platforma iDava.ro, cu sediul lucrativ în România, București, Sector 5, Electromagnetica Business Park („Societatea” sau „Noi”) și persoanele care utilizează („Utilizatorul”) pagina de internet www.iDava.ro („Site-ul” sau „iDava.ro”) și/sau serviciile oferite de Societate prin intermediul Site-ului („Serviciile”).\nAccesarea și utilizarea Site-ului, inclusiv a oricărei pagini sau secțiuni componente ale acestora, sau a oricărui Serviciu furnizat prin intermediul Site-ului se poate face numai în conformitate cu prezentele Termeni și Condiții, care includ Politica de Confidențialitate și Politica privind Cookie-urile.\n \n Pentru a asigura respectarea condițiilor de acces și utilizare a Serviciilor, Utilizatorii trebuie să verifice, la momentul fiecărei accesări a Site-ului, Termenii și Condițiile de utilizare. Trebuie știut că omiterea analizării Termenilor și Condițiilor, dar utilizarea de către dumneavoastră a platformei iDava.ro presupune acceptarea acestui set de Termeni și Condiții (inclusiv orice actualizare a acestora).\n \n Acceptarea acestor Termeni și Condiții presupune că dumneavoastră înțelegeți să respectați politica noastră, astfel că aveți obligația de a nu posta informații ce conținut un limbaj nepotrivit sau care au un conținut discriminatoriu.\n \n Dacă nu sunteți de acord cu prevederile din acest set de Termeni și Condiții (inclusiv orice actualizare a acestuia), vă rugăm să nu utilizați, sau după caz, să încetați utilizarea Site-ului sau a Serviciilor oferite de Noi, după caz.',
    '2.1': '2. Serviciile iDava.ro',
    '2.2':
        'Platforma iDava.ro oferă servicii către:\n-Utilizatori\n-Vizitatori\n-Utilizatori Clienți ',
    '3.0': '2.1. Crearea contului de Client, parole și responsabilități',
    '3.1':
        'Utilizatorii Vizitatori pot folosi anumite facilități oferite de Platforma iDava.ro și fără a avea un cont de Utilizator.\nPentru a beneficia de toate Serviciile oferite de Platforma iDava.ro, Utilizatorii Vizitatori trebuie să solicite o ofertă pe platforma iDava.ro, completând formularul disponibil în interfața secțiunii respective.\nPentru a folosi Serviciile oferite de Platforma iDava.ro, este necesar ca datele furnizate să fie adevărate, exacte și complete. Prin bifarea căsuței: "Confirm că datele introduse mai sus sunt reale" Utlizatorul Vizitator confirmă, în mod liber și neechivoc, că datele sunt conforme cu realitatea.\nTrebuie să ştiţi că datele personale pe care le-am colectat de la dumneavoastră pot fi accesate doar de echipa noastră şi, în cazuri excepţionale, doar în urma unui demers legal, de instituţiile publice din România care aplică legea. Prin bifarea căsuței: "Accept să fiu contactat/ă" Utlizatorul Vizitator confirmă, în mod liber și neechivoc, că este de acord ca un membru al echipei să ia legătura cu el.',
    '4.0': '3. Protecția Contului de Utilizator',
    '4.1':
        'Accesul dumneavoastră la contul de Utilizator al Platformei iDava.ro este protejat de o parolă, motiv pentru care vă recomandăm ca parola să nu fie dezvăluită niciunei alte persoane. De asemenea, vă recomandăm să ieșiți din contul de Utilizator la sfârșitul fiecărei sesiuni de utilizare și, totodată, să închideți fereastra browserului în care ați lucrat la sfârșitul navigării dumneavoastră în platforma iDava.ro.\nAceste sfaturi sunt destinate să înlăture accesul persoanelor neautorizate la informațiile dumneavoastră personale sau la corespondența dumneavoastră, motiv pentru care sunteți răspunzători de păstrarea confidențialității asupra informaților și a parolei dumneavoastră. Veți fi răspunzători de utilizarea înregistrării dumneavoastră, indiferent dacă utilizarea se face cu sau fără voia dumneavoastră. Sunteți de acord să sesizați platforma iDava.ro în legătură cu orice utilizare neautorizată a datelor dumneavoastră de înregistrare în Platforma iDava.ro. Platforma nu va fi răspunzătoare pentru nicio pagubă morală sau materială provocată prin nerespectarea de către dumneavoastră a măsurilor de securitate a datelor utilizate pentru accesarea ei.',
    'nicio_radiografie': 'Nicio radiografie',
    'momentanFaraDocumente':
        'Momentan nu au fost găsite documente în dosarul dumneavoastră electronic',
  },

  'radiografieDimensiuneReala': {
    'imagineNedisponibila': 'Imaginea nu este disponibilă.',
    'descarca': 'Descarcă',
    'salut': 'Salut',
  },

  'completareDateFacturare': {
    'titlu': 'Date necesare plății',
    'cnpParinte': 'CNP părinte',
    'cnpCopil': 'CNP copil',
    'validareCNP': 'Introduceți un CNP valid',
    'completatiToateCampurile': 'Completați toate câmpurile',
    'completatiCnpParinte': 'Completați CNP-ul părintelui!',
    'completatiCnpCopil': 'Completați CNP-ul copilului!',
    'completatiJudetul': 'Completați județul!',
    'completatiLocalitatea': 'Compila la località!',
  },

  'textPaginaNetopia': {
    'textCentrat':
        'Ați fost redirecționat către pagina NETOPIA, pentru a finaliza PLATA serviciului selectat. Această plată este SECURIZATĂ, datele dumneavoastră fiind în SIGURANȚĂ.'
  },

  'voucher': {
    'title': 'Voucher',
    'nuAuFostGasiteVouchere':
        'Momentan nu au fost gasite vouchere în dosarul dumneavoastra electronic',
    'nuUitaMaiBineSaTratezi': 'Nu uita: Mai bine să previi decât să tratezi!',
    'perioadaValabilitate': 'Perioadă valabilitate ',
    'valoare': 'Valoare: ',
  },

  'alegeListaSpecializare': {
    'listaGoala': 'Listă goală',
  },

  'dosarulMeu': {
    'msgMomentanNuAuFostGasiteDocumente':
        'Momentan nu au fost găsite consultații în dosarul dumneavoastră electronic',
  },

  'editJudet': {
    'alegeJudetul': 'Alegeți județul',
    'selecteazaJudetul': 'Selectează județul',
    'cautaJudetul': 'Căutați un județ...',
  },

  'editLocalitate': {
    'alegeLocalitatea': 'Alegeți localitatea',
    'selecteazaLocalitatea': 'Selectează localitate',
    'cautaLocalitatea': 'Căutați o localitate...',
  },
};
